### ISSUE TITLE
RuntimeError: cudaEventSynchronize in future::wait: device-side assert triggered

### ISSUE THREAD

**Issue by MichaelLiang12** [JDAI-CV/DCL#16]
I can run it only for a few steps.
```
ljy@scw4750:~/liang-codes/DCL-master$ python train.py --data CUB --epoch 360 --backbone resnet50                     --tb 16 --tnw 16 --vb 512 --vnw 16                     --lr 0.0008 --lr_step 60                     --cls_lr_ratio 10 --start_epoch 0                     --detail training_descibe --size 512                     --crop 448 --cls_mul --swap_num 7 7
Namespace(auto_resume=False, backbone='resnet50', base_lr=0.0008, check_point=5000, cls_2=False, cls_lr_ratio=10.0, cls_mul=True, crop_resolution=448, dataset='CUB', decay_step=60, discribe='training_descibe', epoch=360, resize_resolution=512, resume=None, save_point=5000, start_epoch=0, swap_num=[7, 7], train_batch=16, train_num_workers=16, val_batch=512, val_num_workers=16)
Choose model and train set
resnet50
train from imagenet pretrained models ...
Set cache dir
the num of new layers: 4
step:        1 / 375 loss=ce_loss+swap_loss+law_loss: 11.6468 = 5.2024 + 6.0823 + 0.3620 
step:        2 / 375 loss=ce_loss+swap_loss+law_loss: 11.6235 = 5.2029 + 5.9551 + 0.4655 
step:        3 / 375 loss=ce_loss+swap_loss+law_loss: 11.7090 = 5.1929 + 6.0129 + 0.5033 
step:        4 / 375 loss=ce_loss+swap_loss+law_loss: 11.6939 = 5.3655 + 5.9946 + 0.3338 
step:        5 / 375 loss=ce_loss+swap_loss+law_loss: 11.6287 = 5.3284 + 5.9917 + 0.3086 
step:        6 / 375 loss=ce_loss+swap_loss+law_loss: 12.3495 = 5.6930 + 6.1811 + 0.4753 
step:        7 / 375 loss=ce_loss+swap_loss+law_loss: 12.0914 = 5.4335 + 6.0904 + 0.5675 
step:        8 / 375 loss=ce_loss+swap_loss+law_loss: 12.1460 = 5.6956 + 6.1155 + 0.3348 
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [2,0,0] Assertion `t >= 0 && t < n_classes` failed.
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [3,0,0] Assertion `t >= 0 && t < n_classes` failed.
CUDA error after cudaEventDestroy in future dtor: device-side assert triggeredTraceback (most recent call last):
  File "train.py", line 229, in <module>
    checkpoint=args.check_point)
  File "/home/ljy/liang-codes/DCL-master/utils/train_model.py", line 111, in train
    law_loss = add_loss(outputs[2], swap_law) * gamma_
  File "/home/ljy/anaconda3/envs/p36c8ljy/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ljy/anaconda3/envs/p36c8ljy/lib/python3.6/site-packages/torch/nn/modules/loss.py", line 85, in forward
    reduce=self.reduce)
  File "/home/ljy/anaconda3/envs/p36c8ljy/lib/python3.6/site-packages/torch/nn/functional.py", line 1558, in l1_loss
    input, target, size_average, reduce)
  File "/home/ljy/anaconda3/envs/p36c8ljy/lib/python3.6/site-packages/torch/nn/functional.py", line 1537, in _pointwise_loss
    return lambd_optimized(input, target, size_average, reduce)
RuntimeError: cudaEventSynchronize in future::wait: device-side assert triggered

```

**Comment by akira-l** [comment]
labels should start from 0

**Comment by MichaelLiang12** [comment]
Thank you. I just used the `train.txt` offered by the author. 

Starting from 0 solved my problem.

**Comment by MichaelLiang12** [comment]
Thank you. I just used the `train.txt` offered by the author.

Starting from 0 solved my problem.
