### ISSUE TITLE
TypeError: can't convert np.ndarray of type numpy.str_.

### ISSUE THREAD

**Issue by EchoWang99** [JDAI-CV/DCL#49]
evaluating val ...
Traceback (most recent call last):
  File "train.py", line 228, in <module>
    checkpoint=args.check_point)
  File "/home/wmj/DCL/utils/train_model.py", line 139, in train
    val_acc1, val_acc2, val_acc3 = eval_turn(Config, model, data_loader['val'], 'val', epoch, log_file)
  File "/home/wmj/DCL/utils/eval_model.py", line 43, in eval_turn
    labels = Variable(torch.from_numpy(np.array(data_val[1])).long().cuda())
TypeError: can't convert np.ndarray of type numpy.str_. The only supported types are: float64, float32, float16, int64, int32, int16, int8, uint8, and bool.

How can I solve this issue?

**Comment by EchoWang99** [comment]
well, I have solved this by myself.
np_val = np.array(data_val[1])
np_val = np_val.astype(int)
