### ISSUE TITLE
CUDA Error while running the code

### ISSUE THREAD

**Issue by rupaliasma** [JDAI-CV/DCL#5]
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1556653215914/work/aten/src/THCUNN/generic/ClassNLLCriterion.cu line=110 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "mytrain2.py", line 146, in <module>
    save_dir=save_dir)
  File "/media/HDD_3TB2/rupali/Code/DCL/utils/train_util_DCL.py", line 60, in train
    loss = criterion(outputs[0], labels)
  File "/home/rupali/anaconda3/envs/EnvPytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/rupali/anaconda3/envs/EnvPytorch/lib/python3.7/site-packages/torch/nn/modules/loss.py", line 942, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "/home/rupali/anaconda3/envs/EnvPytorch/lib/python3.7/site-packages/torch/nn/functional.py", line 2056, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/home/rupali/anaconda3/envs/EnvPytorch/lib/python3.7/site-packages/torch/nn/functional.py", line 1871, in nll_loss
    ret = torch._C._nn.nll_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1556653215914/work/aten/src/THCUNN/generic/ClassNLLCriterion.cu:110

**Comment by akira-l** [comment]
have you ever change the class number ? Labels in elder version are start from 1 in annotation files.

**Comment by akira-l** [comment]
feel free to open a new issue if you meet other problems :)
